[package]
name = "drones"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = "1.0.206"
serde_json = "1.0.124"
utils = { path = "../utils" }
client = { path = "../client" }
protocol = { path = "../protocol" }
broker = { path = "../broker" }
rand = "0.8.5"
egui = "0.28.1"
