[workspace]
resolver = "2"

members = [
    "broker", "camera_system",
    "client", "drones", "tests", 
    "monitoring_app",
    "protocol",
    "rustic_city_eye", 
    "ui", 
    "utils"]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
