[workspace]
resolver = "2"

members = [
    "broker", "camera_system",
    "client", "drones", "integration_tests", 
    "monitoring_app",
    "protocol",
    "rustic_city_eye", 
    "ui", 
    "utils"]
