[package]
name = "camera_system"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../client" }
protocol = { path = "../protocol" }
utils = { path = "../utils" }
broker = { path = "../broker" }

rand = "0.8.5"
