[package]
name = "rustic_city_eye"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rand = "0.8.5"

[[bin]]
name = "broker"
path = "src/mqtt/run_broker.rs"

[[bin]]
name = "monitoring_app"
path = "src/monitoring_app/run_monitoring.rs"

[[bin]]
name = "camera_system"
path = "src/camera_system/run_camera_system.rs"