[package]
name = "rustic_city_eye"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
mockall = "0.12.1"
walkers = "=0.8.0"
webkit2gtk = "2.0.1"
osmgpsmap = "0.2.16"
egui = "0.27.2"
eframe = "0.27.2"

[[bin]]
name = "broker"
path = "src/mqtt/run_broker.rs"

[[bin]]
name = "monitoring_app"
path = "src/monitoring/main.rs"
