[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
rand = "0.8.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = "1.0.206"
serde_json = "1.0.124"
tempdir = "0.3.7"
