[package]
name = "broker"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol" }
utils = { path = "../utils" }

rustls = "0.23.12"
rustls-pemfile = "2.1.3"
serde = { version = "1.0", features = ["derive"] }
