name: ci


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: libsoup
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install libsoup-3.0-dev
        sudo apt-get install libjavascriptcoregtk-4.0-dev
        sudo apt-get install libwebkit2gtk-4.1-dev
        sudo apt-get install libosmgpsmap-1.0-dev
        sudo apt-get install libpango1.0-dev
        sudo apt-get install libcairo2-dev
        sudo apt install libatk1.0-dev
        sudo apt install libgdk-pixbuf2.0-dev



    - name: Change to subdirectory
      run: cd rustic_city_eye
    - name: add crates
      run: cargo add javascriptcore-rs-sys
      working-directory: rustic_city_eye
    - name: Setup paths and env
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
      working-directory: rustic_city_eye
    - name: Clean
      run: cargo clean
      working-directory: rustic_city_eye
    - name: Build
      run: cargo build --verbose
      working-directory: rustic_city_eye
    - name: Run tests
      run: cargo test -- --test-threads=1
      working-directory: rustic_city_eye
    - name: Run clippy
      run: cargo clippy --all-targets --all-features
      working-directory: rustic_city_eye
